/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/dialogs/ConfirmDialog.vue')['default']
    CreateOrEditProducts: typeof import('./src/components/dialogs/CreateOrEditSalas.vue')['default']
    CreateOrEditUsers: typeof import('./src/components/dialogs/CreateOrEditUsuarios.vue')['default']
    DefaultTable: typeof import('./src/components/DefaultTable.vue')['default']
    MapDialog: typeof import('./src/components/dialogs/MapDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
